INSERT INTO USERS(USERNAME,PASSWORD,CURRENT_ROLE,ACTIVE) VALUES ('admin','password','ROLE_ADMIN', true);
INSERT INTO USERS(USERNAME,PASSWORD,CURRENT_ROLE,ACTIVE)  VALUES ('superadmin','password123','ROLE_SUPER_ADMIN', true);
INSERT INTO USERS(USERNAME,PASSWORD,CURRENT_ROLE,ACTIVE)  VALUES ('Souma','1234','ROLE_USER', true);
INSERT INTO USERS(USERNAME,PASSWORD,CURRENT_ROLE,ACTIVE) VALUES ('Sam','0987','ROLE_USER', true);
